### ISSUE TITLE
Not pulling latest version on Unraid

### ISSUE THREAD

**Issue by pysanders** [packetworks/docker-nxfilter#10]
Due to the way Unraid mounts the the persistent data the curl script is failing to download latest version. If we add "-p" to mkdir and "-o" to unzip this appears to solve this problem. Can we incorporate that into the docker-file?

>   curl -s -L http://www.nxfilter.org/|grep Download \
>   |grep -Eo "(http|https)://[a-zA-Z0-9./?=_-]*" \
>   |grep download|uniq \
>   |xargs -n1 curl -s -L \
>   |grep -Eo "(http|https)://[a-zA-Z0-9./?=_-]*" \
>   |grep filter-.*zip|grep -v mediafire \
>   |xargs -n1 wget -q && mkdir -p /nxfilter \
>   && unzip -o nxfil* -d /nxfilter \
>   && chmod +x /nxfilter/bin/startup.sh \
>   && rm -f *.zip

**Comment by cron410** [comment]
Certainly can.
