### ISSUE TITLE
nxfilter RHiAD, License blocked by endDate

### ISSUE THREAD

**Issue by jeanpaulrh** [packetworks/docker-nxfilter#17]
Hi,
I installed the docker image yesterday and everything went fine.
Today I saw a bunch of blocked items with a "License issue" or something in red.
In the log I found this line repeated:
"nxfilter RHiAD, License blocked by endDate".

I assume it has to do with the Jahaslist licence, but I don't know how to solve it.
On the site I read that there's a free license for 25 users.
Now I'm on Globlist but Jahaslist was more complete.

Thanks,

    Gianpaolo

**Comment by cron410** [comment]
Sorry I missed this, but that sounds like an issue with NxFilter and not the Docker image. I'll be closing this one unless you have a direct issue with running in Docker.
