### ISSUE TITLE
Start Error

### ISSUE THREAD

**Issue by ghost** [packetworks/docker-nxfilter#18]
My Raspberry Pi 4 Model B of 2GB of RAM runs Docker, however, when trying to run NxFilter, I have the following error:

standard_init_linux.go:219: exec user process caused: exec format error

**Comment by tbartlomiejczyk** [comment]
I had the same issue. I solved it by using pi-experimental tag.
https://hub.docker.com/layers/packetworks/nxfilter-base/pi-experimental/images/sha256-ccff6d0e6d7564aefdc714c93cb3fe9ac542672c2c7a013937084a4cfc1e8021?context=explore

**Comment by ghost** [comment]
Thanks!

Solved my problem.


----------
Welbert Miranda

Em dom, 14 de mar de 2021 11:43 AM, tbartlomiejczyk <
***@***.***> escreveu:

**Comment by cron410** [comment]
Glad it worked for you. I'm still working out some scripting issues on that branch, but it's only preventing new builds. Eventually, Pi support will be in the `latest` tag when they are sorted.
