### ISSUE TITLE
Error: executable file `/entrypoint.sh` not found in $PATH: No such file or directory: OCI not found

### ISSUE THREAD

**Issue by marafa** [packetworks/docker-nxfilter#19]
whenever i run the image i get this error now `Error: executable file `/entrypoint.sh` not found in $PATH: No such file or directory: OCI not found`

is it related to yesterdays change to github actions?

**Comment by marafa** [comment]
hmm .. i see this https://github.com/packetworks/docker-nxfilter/commit/6deb744ab60314bb0ce6d5c5b5fa9bc9ed37dcd2#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R8

**Comment by cron410** [comment]
Looks like I added a `./` for the `COPY` command which isn't quite correct for this image. Just added a fix and tested it in my local system with no issues. Changes have been pushed to Docker Hub for build.

**Comment by marafa** [comment]
fixed! 
thank you!
