### ISSUE TITLE
Make Dockerfile pull the latest .zip from the website

### ISSUE THREAD

**Issue by cron410** [packetworks/docker-nxfilter#3]
I'm trying to figure out how to make the Dockerfile wget or curl the latest .zip from the nxfilter website. https://github.com/packetworks/docker-nxfilter/blob/nxfilter-experimental/Dockerfile

The idea is use IFTTT to trigger a build on Docker Hub whenever the Downloads page changes. It can be monitored by page2rss on IFTTT which can then make a web hook to Docker Hub to trigger the build.

**Comment by cron410** [comment]
@brugnara do you have any tips?

**Comment by brugnara** [comment]
@cron410 look at this page. Maybe it is simpler finding the link from this. You can assume the first zip link is the one you want. 
http://www.nxfilter.org/download.php

Another method should be to ask nxfilter team to create a latest link which points to the last version and put the run commands into one ONBUILD docker command. Just thinking..

**Comment by cron410** [comment]
`RUN wget --spider --force-html -r -l1 \`
`http://www.nxfilter.org/download.php 2>&1 \`
`| grep '^--' | awk '{ print $3 }' \`
`| grep 'nxfilter-' | grep 'zip' \`
`| grep -v 'cloud' | head -n1 > url.txt \`
`&& wget -i url.txt`

This is as simple and concise as I can get. What do you think?

**Comment by cron410** [comment]
ad47427
